# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudecost < Formula
  desc "Claude conversation cost analyzer"
  homepage "https://git.ceh.im/cehoffman/claudecost"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_darwin_amd64.tar.gz"
      sha256 "09af372d829d06efeffd13ddfc521e857236e4f8825599c163fc8aa91e9c3180"

      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_darwin_arm64.tar.gz"
      sha256 "5eb395e936533ba3f86bdc390eba186daaf18fff10689e7462065424c3edf326"

      def install
        bin.install "claudecost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_linux_amd64.tar.gz"
      sha256 "dac241f416d116545fa317d0c4bb445b3837bb642319f560e2aa8dbf80798c36"
      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_linux_arm64.tar.gz"
      sha256 "2a5747653c286cd1c4168d52f8e77964080cdbcf35451790d05bb3470fbfe4fe"
      def install
        bin.install "claudecost"
      end
    end
  end

  test do
    system "#{bin}/claudecost", "--version"
  end
end
