# This file was generated by GoReleaser. DO NOT EDIT.
cask "aistat" do
  desc "AI contribution statistics analyzer"
  homepage "https://git.ceh.im/cehoffman/aistats"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aistat"

  on_macos do
    on_intel do
      url "https://git.ceh.im/cehoffman/aistats/releases/download/v0.1.0/aistat_Darwin_x86_64.tar.gz"
      sha256 "4d58e3887214f64ea75e2369af8961c3b2f036410ee06c3ddad0f011e324a74f"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/aistats/releases/download/v0.1.0/aistat_Darwin_arm64.tar.gz"
      sha256 "75bd5b23c24958e4315bdaff9cf5029ad680fc6dc8c3dd3ed45f3bc752c0b67d"
    end
  end

  on_linux do
    on_intel do
      url "https://git.ceh.im/cehoffman/aistats/releases/download/v0.1.0/aistat_Linux_x86_64.tar.gz"
      sha256 "574a5ddb20f835bd295d8abb9b4e49c074dc127d8d196486a87cd3d54100094d"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/aistats/releases/download/v0.1.0/aistat_Linux_arm64.tar.gz"
      sha256 "f1b0b75a8f68d8042eb27960e4dae0f9e0c06ee7d5905e371a03758b0d123cf6"
    end
  end

  # No zap stanza required
end
