# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudecost" do
  name "claudecost"
  desc "Claude conversation cost analyzer"
  homepage "https://git.ceh.im/cehoffman/claudecost"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudecost"

  on_macos do
    on_intel do
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v#{version}/claudecost_Darwin_x86_64.tar.gz"
      sha256 "7330e7835709481a36fd852782f84ea4d1b2c4d5bcbd0f0975619575a9aaf5d3"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v#{version}/claudecost_Darwin_arm64.tar.gz"
      sha256 "b2154c623be6e3116ed4be9e83795b07eaed9081f97039e13307749d39aad6ea"
    end
  end

  on_linux do
    on_intel do
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v#{version}/claudecost_Linux_x86_64.tar.gz"
      sha256 "caf0571a636104c693baa5d5e2dd6d439f9256d9c012c350c42e8237dc782892"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v#{version}/claudecost_Linux_arm64.tar.gz"
      sha256 "607e9f7d86562b1dc89c6eee0e826f9814a89d050c3dfc6e0f8f8c64b22012e1"
    end
  end

  # No zap stanza required
end
