# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitpulse" do
  desc "Git repository pulse visualization tool"
  homepage "https://git.ceh.im/cehoffman/gitpulse"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitpulse"

  on_macos do
    on_intel do
      url "https://git.ceh.im/cehoffman/gitpulse/releases/download/v1.0.0/gitpulse_Darwin_x86_64.tar.gz"
      sha256 "a74685992b7f0268781435e58e4adc3b89574ce71c050343429fcb71bb20a33f"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/gitpulse/releases/download/v1.0.0/gitpulse_Darwin_arm64.tar.gz"
      sha256 "8d9fc3417d6bf27d4dd478c5060689ebfbbb4e7fb5470f2dbe97a5c70a755132"
    end
  end

  on_linux do
    on_intel do
      url "https://git.ceh.im/cehoffman/gitpulse/releases/download/v1.0.0/gitpulse_Linux_x86_64.tar.gz"
      sha256 "bb98637e7926797cac1aed930fce0d6ddead776c7279cf940bcd0b568f1cde36"
    end
    on_arm do
      url "https://git.ceh.im/cehoffman/gitpulse/releases/download/v1.0.0/gitpulse_Linux_arm64.tar.gz"
      sha256 "b875fe0b6399e76b16d973275521fc87a76f44a3b8b1f52be58f3758eb8a3add"
    end
  end

  # No zap stanza required
end
