# This file was generated by GoReleaser. DO NOT EDIT.
cask "gpg-extend" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4f39d4257877d7283869c1bd4133ba6a4b8cc0a30e7e8b4e67e8993b5bfd3f66"
      url "https://git.ceh.im/cehoffman/gpg-extend/releases/download/v#{version}/gpg-extend_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "592d790567d0a22e11a4518df4522b5e8c4d634d8f35866315f03e83bb8352e8"
      url "https://git.ceh.im/cehoffman/gpg-extend/releases/download/v#{version}/gpg-extend_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0025b4988bfa676b61ca23ee8ddf081f35136f28672eaa9f97de70e3bc42345"
      url "https://git.ceh.im/cehoffman/gpg-extend/releases/download/v#{version}/gpg-extend_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "110f6a78cc1032277b300a4d4172793707f8b0628005a9d588b04e8dcb6f38ed"
      url "https://git.ceh.im/cehoffman/gpg-extend/releases/download/v#{version}/gpg-extend_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gpg-extend"
  desc "Maintain and distribute a Bitwarden-backed GPG key"
  homepage "https://git.ceh.im/cehoffman/gpg-extend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gpg-extend"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gpg-extend"]
  end

  # No zap stanza required

end
