# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudecost < Formula
  desc "Claude conversation cost analyzer"
  homepage "https://git.ceh.im/cehoffman/claudecost"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.5.0/claudecost_0.5.0_darwin_amd64.tar.gz"
      sha256 "f5b73221093dba06db0f855d4e69fe92c8e8592b2590b389ffbf7f77ee0266ba"

      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.5.0/claudecost_0.5.0_darwin_arm64.tar.gz"
      sha256 "3bac2de5a4a0aff2705819cafd8bf884b231641853fb0d67bdb974a96f3e9ec6"

      def install
        bin.install "claudecost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.5.0/claudecost_0.5.0_linux_amd64.tar.gz"
      sha256 "2a097466eefba7b9a45ede17dae5fa64913397efa19874804f1e9a196a988098"
      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.5.0/claudecost_0.5.0_linux_arm64.tar.gz"
      sha256 "d6a5cc758554c7fcdc13d36160192df7b95eac8bab11a707c26257d7454d7357"
      def install
        bin.install "claudecost"
      end
    end
  end

  test do
    system "#{bin}/claudecost", "--version"
  end
end
