# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudecost < Formula
  desc "Claude conversation cost analyzer"
  homepage "https://git.ceh.im/cehoffman/claudecost"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_darwin_amd64.tar.gz"
      sha256 "0c3a9ff2f6e945d81b8087efd0ac626c82b161e1e62bdb0e228116be7a8382b6"

      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_darwin_arm64.tar.gz"
      sha256 "d493fc571e584329e3827bc236fdee4e57c75ce7388cf0dafeaf17f8f26067d6"

      def install
        bin.install "claudecost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_linux_amd64.tar.gz"
      sha256 "819b758aec1476a9e351a0e1b47076f6ada920b6099ef1fbfe6293339d5e0782"
      def install
        bin.install "claudecost"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/claudecost/releases/download/v0.2.0/claudecost_0.2.0_linux_arm64.tar.gz"
      sha256 "2f287f35d5c67b40158b9a315a0589966c9eaffd8d16eda42d865063530ebbe3"
      def install
        bin.install "claudecost"
      end
    end
  end

  test do
    system "#{bin}/claudecost", "--version"
  end
end
