# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "Splits plain JSON logs into beautiful colored output"
  homepage "https://git.ceh.im/cehoffman/prism"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_darwin_amd64.tar.gz"
      sha256 "7606e0f4f977ef06fb101907d404dadfc66872ebb35d305be35539916a3c6fb9"

      def install
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_darwin_arm64.tar.gz"
      sha256 "ca2c67f75294fa0391855e61325444cf17f8ea72409ae0f06674d8d9f4d15461"

      def install
        bin.install "prism"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_linux_amd64.tar.gz"
      sha256 "3211fa93ecb36a8c652aa972269b4d1af51d99ba444671963680514068d51492"
      def install
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_linux_arm64.tar.gz"
      sha256 "91464a9a1fa8c29229616ea569ec9b198def3de2c99507b0e6d66c1f4c04511d"
      def install
        bin.install "prism"
      end
    end
  end

  test do
    system "#{bin}/prism", "--version"
  end
end
