# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "Splits plain JSON logs into beautiful colored output"
  homepage "https://git.ceh.im/cehoffman/prism"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_darwin_amd64.tar.gz"
      sha256 "ce95e29e69b4a1c059ee538c943060cd707a00c43366940816db2341ae5823c8"

      def install
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_darwin_arm64.tar.gz"
      sha256 "cbb799a8222b28e29e1a74ace44819784b6d012b0d13df35f748e0e5f8920ece"

      def install
        bin.install "prism"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_linux_amd64.tar.gz"
      sha256 "478a3195420508ffb5f4bd31687a5c83a174145545e609c698a7ce477515fcbb"
      def install
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://git.ceh.im/cehoffman/prism/releases/download/v0.1.0/prism_0.1.0_linux_arm64.tar.gz"
      sha256 "c5c5ccd13af0b64efd6c47a29c17ff4c0b150dcfeef2d0c3e2a3179d8c521c12"
      def install
        bin.install "prism"
      end
    end
  end

  test do
    system "#{bin}/prism", "--version"
  end
end
